/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Instalador.java
 *
 * Created on 25/11/2017, 11:41:30 AM
 */
package marketplace;

import java.util.Calendar;
import java.util.List;

/**
 *
 * @author jairo
 */
public class Instalador extends javax.swing.JFrame {

    /** Creates new form Instalador */
    public Instalador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkBasico = new javax.swing.JCheckBox();
        chkCompras = new javax.swing.JCheckBox();
        chkPSE = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tRutaPropiedades = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tLog = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tComandoMaven = new javax.swing.JTextField();
        rbTXT = new javax.swing.JRadioButton();
        rbXML = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instalador MarketPlace");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("INSTALADOR MARKET PLACE");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketplace/modeloFeatures.JPG"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        chkBasico.setSelected(true);
        chkBasico.setText("Market Place Basico");
        chkBasico.setToolTipText("");
        chkBasico.setName("mkBasico"); // NOI18N
        chkBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBasicoActionPerformed(evt);
            }
        });

        chkCompras.setText("Market Place Compras");
        chkCompras.setToolTipText("Implementar Feature Compras");
        chkCompras.setName("chkCompras"); // NOI18N
        chkCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkComprasActionPerformed(evt);
            }
        });

        chkPSE.setText("Pago PSE");
        chkPSE.setToolTipText("Implementar Pago con PSE");
        chkPSE.setName("chkPSE"); // NOI18N
        chkPSE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkPSEStateChanged(evt);
            }
        });
        chkPSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPSEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Selección Caracteristicas a Implementar");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(chkPSE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBasico, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(chkCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(chkBasico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPSE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Ruta archivo Propiedades:");
        jLabel4.setName("jLabel4"); // NOI18N

        tRutaPropiedades.setText("./");
        tRutaPropiedades.setToolTipText("Ruta de la carpeta termina en / .ej.: c:/temp/");
        tRutaPropiedades.setName("tRutaPropiedades"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tLog.setColumns(20);
        tLog.setEditable(false);
        tLog.setRows(5);
        tLog.setName("tLog"); // NOI18N
        jScrollPane1.setViewportView(tLog);

        jLabel6.setText("Log:");
        jLabel6.setName("jLabel6"); // NOI18N

        jButton1.setLabel("Instalar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ejecutar");
        jLabel7.setName("jLabel7"); // NOI18N

        tComandoMaven.setName("tComandoMaven"); // NOI18N

        buttonGroup1.add(rbTXT);
        rbTXT.setSelected(true);
        rbTXT.setText("Logger TXT");
        rbTXT.setName("rbTXT"); // NOI18N

        buttonGroup1.add(rbXML);
        rbXML.setText("Logger XML");
        rbXML.setName("rbXML"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbXML)
                                            .addComponent(rbTXT))))
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tComandoMaven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(tRutaPropiedades)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(rbTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbXML)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tRutaPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tComandoMaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBasicoActionPerformed
        // TODO add your handling code here:
        Object[] selectedObjects = chkBasico.getSelectedObjects();        
        if(selectedObjects != null){
            chkCompras.setSelected(false);
            chkPSE.setSelected(false);
        }
    }//GEN-LAST:event_chkBasicoActionPerformed

    private void chkPSEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkPSEStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_chkPSEStateChanged

    private void chkPSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPSEActionPerformed
        // TODO add your handling code here:
        Object[] selectedObjects = chkPSE.getSelectedObjects();        
        if(selectedObjects != null){
            chkCompras.setSelected(true);
            chkBasico.setSelected(false);
        }
    }//GEN-LAST:event_chkPSEActionPerformed

    private void chkComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkComprasActionPerformed
        // TODO add your handling code here:
        Object[] selectedObjects = chkCompras.getSelectedObjects();
        if(selectedObjects == null){
            chkPSE.setSelected(false);
        }else{
            chkBasico.setSelected(false);
        }
    }//GEN-LAST:event_chkComprasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean featureBASICO= chkBasico.getSelectedObjects() != null; 
        boolean featureCOMPRAS = chkCompras.getSelectedObjects() != null;
        boolean featurePSE = chkPSE.getSelectedObjects() != null;
        boolean loggerTXT = rbTXT.isSelected();
        boolean loggerXML = rbXML.isSelected();
        
        
          
        boolean[] features = {featureBASICO,featureCOMPRAS,featurePSE,loggerTXT,loggerXML};
        
        String rutaProperties = tRutaPropiedades.getText().trim();
        String comandoMaven = tComandoMaven.getText().trim();
        String res="";
        tLog.setText(null);
        if(!featureBASICO && !featureCOMPRAS){
            tLog.append("DEBE SELECCIONAR UN PRODUCTO!");
            return;
        }
        tLog.append(Calendar.getInstance().getTime().toString()+"\n");
        tLog.append("Seleccion realizada: \nBasico="+featureBASICO+ " \nCompras="+ featureCOMPRAS +" \nPSE="+ featurePSE +"\nLogger TXT="+loggerTXT+"\nLogger XML="+loggerXML+"\n");
        tLog.append("Archivo propiedades : "+rutaProperties+"\n");
        tLog.append("Ejecutar: "+comandoMaven );
        
        tLog.append("\n---------CARGAR COMANDOS------------");
        
        List<String> comandos = new ManejaArchivo().cargarArchivo("/marketplace/comandos.txt");
        tLog.append("\nComandos cargados : "+comandos.size());
        
        tLog.append("\n---------CREAR ARCHIVO PROPIEDADES-------------");
        if(!rutaProperties.equals("")){
            res = new ManejaArchivo(rutaProperties,features).crearArchivoXML();
            tLog.append("\n"+res);
            res = new ManejaArchivo(rutaProperties,features).crearArchivoTXT();
            tLog.append("\n"+res);
        }else{
            tLog.append("\n Ruta vacia no se crea archivo propiedades!");
        }
        
        tLog.append("\n---------EJECUTAR COMANDOS-------------");
        if(!comandoMaven.equals("")){
            res = new EjecutarComandos().ejecutar(comandoMaven);
            tLog.append("\n"+res);
        }else{            
            if(comandos.size()>0 && !comandos.get(0).equals("")){
                String[] cmds = comandos.toArray(new String[comandos.size()]);
                res = new EjecutarComandos().ejecutar(cmds);
                tLog.append("\n"+res);
            }
            tLog.append("\n---------EJECUTAR COMANDO DESDE .BAT-------------");
            if(featureBASICO)
                res = new EjecutarComandos().ejecutarBAT("instalarBasico.bat");
            if(featureCOMPRAS)
                res = new EjecutarComandos().ejecutarBAT("instalarCompras.bat");
            tLog.append("\n"+res);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Instalador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBasico;
    private javax.swing.JCheckBox chkCompras;
    private javax.swing.JCheckBox chkPSE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbTXT;
    private javax.swing.JRadioButton rbXML;
    private javax.swing.JTextField tComandoMaven;
    private javax.swing.JTextArea tLog;
    private javax.swing.JTextField tRutaPropiedades;
    // End of variables declaration//GEN-END:variables
}
